# Generated by Django 3.2.9 on 2021-11-15 20:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
