# Generated by Django 3.2.9 on 2021-11-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serice_title',
            new_name='service_title',
        ),
    ]
