# Generated by Django 3.2.9 on 2021-11-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_slug_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug_service',
            new_name='slug',
        ),
    ]
